# Global configuration options
line-length = 88
show-fixes = true

[lint]
select = [
    "F",    # Pyflakes
    "W",    # pycodestyle
    "E",    # pycodestyle
    "I",    # isort
    "UP",   # pyupgrade
    "PL",   # Pylint
    "T201", # Print Statement
    "S",    # flake8-bandit
    "TCH",  # flake8-type-checking
    "RUF",  # Ruff-specific rules
]
ignore = ["E501"]

[lint.isort]
known-first-party = ["kedro"]

[lint.per-file-ignores]
"{tests,docs}/*" = ["PLR2004", "PLR0913"]
"{tests,docs,tools,static,features,docs}/*" = ["T201", "S101", "S108"]

[format]
exclude = ["**/templates", "features/steps/test_starter"]
docstring-code-format = true
